<?php
@include 'config.php';
if(isset($_POST['submit'])){
    $name=mysqli_real_escape_string($conn,$_POST['name']);
    $date=$_POST['date'];
    $gender=$_POST['gender'];
    $email=mysqli_real_escape_string($conn,$_POST['email']);
    $password=md5($_POST['password']);
    $cpassword=md5($_POST['cpassword']);
    $code=$_POST['code'];
    $phone=$_POST['phone'];
    $ugpg=$_POST['ugpg'];
    $university=$_POST['university'];
    $address=$_POST['address'];
    $state=$_POST['state'];
    $zipcode=$_POST['zipcode'];
    $country=$_POST['country'];

    $select="SELECT * FROM  user_info where email = '$email' && password ='$password' ";
    $result = mysqli_query($conn,$select);
    if (mysqli_num_rows($result)>0){
        while($data = mysqli_fetch_assoc($result)){
            $error[]='user already exist !';
        }
    }
    else{
        
        if($password != $cpassword){
            $error[]="Password don't matched !";
        }else{
            $insert = "INSERT INTO user_info (name,date,gender,email,password,code,phone,ugpg,university,address,state,zipcode,country,dt) VALUES ('$name','$date','$gender','$email','$password','$code','$phone','$ugpg','$university','$address','$state','$zipcode','$country',current_timestamp())";
            mysqli_query($conn,$insert);
            $error[]="Thank you for Sign Up";
            //header('location:loginform.php');
        }
    }
};
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>register form</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
<div class="form-container">
    <form action="" method="post">
        <h3>register now</h3>
        <?php
        if(isset($error)){
            foreach($error as $error){
                echo '<span class="error-msg">'.$error.'</span>';
            };
        }
        ?>
        <input type="text" name="name" placeholder="Enter your Full Name" required>

        <input type="text" name="date" id="date" placeholder="Enter your DOB i.e dd-mm-yyyy">

        <select id="gender "name="gender">
            <option select hidden value="">Select your Gender</option>
            <option value="Male">Male</option>
			<option value="Female">Female</option>
			<option value="Others">Others</option>
			<option value="Prefer not to say">Prefer not to say</option>
        </select>

        <input type="email" name="email" placeholder="Enter your E-Mail" required>

        <input type="password" name="password" placeholder="Enter your password" required>

        <input type="password" name="cpassword" placeholder="Confirm your password" required >

        <select id="code" name="code" required >
            <option select hidden value="">Select Country Code</option>
            <option value="+91">+91</option>
        </select>

        <input type="phone" name="phone" id="phone" placeholder="Enter your Phone Number" required>

        <select id="ugpg" name="ugpg">
            <option select hidden value="">Select your Graduation Level</option>
            <option value="UG">UG</option>
            <option value="PG">PG</option>
        </select>

        <select id="university" name="university" required>
            <option select hidden value="">Select your University Name</option>
            <option value="Acharya Nagarjuna University">Acharya Nagarjuna University</option>
            <option value="Bharatiya Engineering Science and Technology Innovation University">Bharatiya Engineering Science and Technology Innovation University</option>
            <option value="Central University of Andhra Pradesh">Central University of Andhra Pradesh</option>
            <option value="Centurion University of Technology and Management">Centurion University of Technology and Management</option>
            <option value="Damodaram Sanjivayya National Law University">Damodaram Sanjivayya National Law University</option>
            <option value="Dr Abdul Haq Urdu University">Dr Abdul Haq Urdu University</option>
            <option value="Dr. B.R. Ambedkar University">Dr. B.R. Ambedkar University</option>
            <option value="Dravidian University">Dravidian University</option>
            <option value="Dr Y.S.R. Horticultural University">Dr Y.S.R. Horticultural University</option>
            <option value="Dr N.T.R. University of Health Sciences (Formerly Andhra Pradesh)">Dr N.T.R. University of Health Sciences (Formerly Andhra Pradesh)</option>
            <option value="University of Health Sciences)">University of Health Sciences)</option>
            <option value="Gandhi Institute of Technology and Management (GITAM)">Gandhi Institute of Technology and Management (GITAM)</option>
            <option value="Jawaharlal Nehru Technological University, Anantpur">Jawaharlal Nehru Technological University, Anantpur</option>
            <option value="Jawaharlal Nehru Technological University, Kakinada">Jawaharlal Nehru Technological University, Kakinada</option>
            <option value="Koneru Lakshmaiah Education Foundation">Koneru Lakshmaiah Education Foundation</option>
            <option value="KREA University">KREA University</option>
            <option value="Krishna University">Krishna University</option>
            <option value="Rajiv Gandhi University of Knowledge Technologies">Rajiv Gandhi University of Knowledge Technologies</option>
            <option value="Rashtriya Sanskrit Vidyapeeth">Rashtriya Sanskrit Vidyapeeth</option>
            <option value="Rayalaseema University">Rayalaseema University</option>
            <option value="Saveetha Amaravati University">Saveetha Amaravati University</option>
            <option value="Sri Krishnadevaraya University">Sri Krishnadevaraya University</option>
            <option value="Sri Padmavati Mahila Vishwavidyalayam">Sri Padmavati Mahila Vishwavidyalayam</option>
            <option value="Sri Sathya Sai Institute of Higher Learning">Sri Sathya Sai Institute of Higher Learning</option>
            <option value="Sri Venkateswara University">Sri Venkateswara University</option>
            <option value="Sri Venkateswara Vedic University,">Sri Venkateswara Vedic University,</option>
            <option value="Sri Venkateswara Veterinary University">Sri Venkateswara Veterinary University</option>
            <option value="Sri Venkateswara Institute of Medical Sciences">Sri Venkateswara Institute of Medical Sciences</option>
            <option value="SRM University">SRM University</option>
            <option value="VIT-AP University">VIT-AP University</option>
            <option value="Apex Professional University, Pasighat">Apex Professional University, Pasighat</option>
            <option value="Arunachal University of Studies">Arunachal University of Studies</option>
            <option value="Arunodaya University">Arunodaya University</option>
            <option value="Himalayan University">Himalayan University</option>
            <option value="North East Frontier Technical University">North East Frontier Technical University</option>
            <option value="North Eastern Regional Institute of Science & Technology">North Eastern Regional Institute of Science & Technology</option>
            <option value="The Global University">The Global University</option>
            <option value="Andhra University">Andhra University</option>
            <option value="The Indira Gandhi Technological & Medical Sciences University">The Indira Gandhi Technological & Medical Sciences University</option>
            <option value="Venkateshwara Open University">Venkateshwara Open University</option>
            <option value="Assam Agricultural University">Assam Agricultural University</option>
            <option value="Assam Don Bosco University">Assam Don Bosco University</option>
            <option value="Assam Down Town University">Assam Down Town University</option>
            <option value="Assam University">Assam University</option>
            <option value="Assam Rajiv Gandhi University of Co-operative Management">Assam Rajiv Gandhi University of Co-operative Management</option>
            <option value="Assam Science & Technology University">Assam Science & Technology University</option>
            <option value="Adikavi Nannaya University">Adikavi Nannaya University</option>
            <option value="Assam Womens University">Assam Womens University</option>
            <option value="Bodoland University">Bodoland University</option>
            <option value="Bhattadev University">Bhattadev University</option>
            <option value="Central Institute of Technology(CIT)">Central Institute of Technology(CIT)</option>
            <option value="Dibrugarh University">Dibrugarh University</option>
            <option value="Gauhati University">Gauhati University</option>
            <option value="Krishna Kanta Handique State Open University">Krishna Kanta Handique State Open University</option>
            <option value="Kumar Bhaskar Varma Sanskrit & Ancient Studies University">Kumar Bhaskar Varma Sanskrit & Ancient Studies University</option>
            <option value="Krishnaguru Adhyatmik Visvavidyalaya">Krishnaguru Adhyatmik Visvavidyalaya</option>
            <option value="Madhabdev University">Madhabdev University</option>
            <option value="Mahapurusha Srimanta Sankaradeva Viswavidyalaya">Mahapurusha Srimanta Sankaradeva Viswavidyalaya</option>
            <option value="National Law University and Judicial Academy">National Law University and Judicial Academy</option>
            <option value="Yogi Vemana University">Yogi Vemana University</option>
            <option value="Rabindranath Tagore University">Rabindranath Tagore University</option>
            <option value="Srimanta Sankaradeva University of Health Sciences">Srimanta Sankaradeva University of Health Sciences</option>
            <option value="Tezpur University">Tezpur University</option>
            <option value="The Assam Kaziranga University">The Assam Kaziranga University</option>
            <option value="The Assam Royal Global University">The Assam Royal Global University</option>
            <option value="AAFT University of Media and Arts">AAFT University of Media and Arts</option>
            <option value="Amity University">Amity University</option>
            <option value="Vignans Foundation for Science, Technology and Research">Vignans Foundation for Science, Technology and Research</option>
            <option value="Ayush and Health Sciences University of Chhattisgarh">Ayush and Health Sciences University of Chhattisgarh</option>
            <option value="Bastar Vishwavidyalaya">Bastar Vishwavidyalaya</option>
            <option value="Atal Bihari Vajpai Vishwavidyalaya (Formerly Bilaspur Vishwavidyalaya)">Atal Bihari Vajpai Vishwavidyalaya (Formerly Bilaspur Vishwavidyalaya)</option>
            <option value="Chhattisgarh Kamdhenu Vishwavidyalaya">Chhattisgarh Kamdhenu Vishwavidyalaya</option>
            <option value="Chhattisgarh Swami Vivekanand Technical University">Chhattisgarh Swami Vivekanand Technical University</option>
            <option value="Dr C.V. Raman University">Dr C.V. Raman University</option>
            <option value="Durg Vishwavidyalaya">Durg Vishwavidyalaya</option>
            <option value="Guru Ghasidas Vishwavidyalaya">Guru Ghasidas Vishwavidyalaya</option>
            <option value="Hidayatullah National Law University">Hidayatullah National Law University</option>
            <option value="ICFAI University">ICFAI University</option>
            <option value="International Institute of Information Technology">International Institute of Information Technology</option>
            <option value="ISBM University">ISBM University</option>
            <option value="Indira Gandhi Krishi Vishwavidyalaya">Indira Gandhi Krishi Vishwavidyalaya</option>
            <option value="Indira Kala Sangeet Vishwavidyalaya">Indira Kala Sangeet Vishwavidyalaya</option>
            <option value="ITM University">ITM University</option>
            <option value="K.K.Modi University">K.K.Modi University</option>
            <option value="Kushabhau Thakre Patrakarita Avam Jansanchar Vishwavidyalaya">Kushabhau Thakre Patrakarita Avam Jansanchar Vishwavidyalaya</option>
            <option value="Kalinga University">Kalinga University</option>
            <option value="Maharishi University of Management and Technology">Maharishi University of Management and Technology</option>
            <option value="MATS University">MATS University</option>
            <option value="O.P. Jindal University">O.P. Jindal University</option>
            <option value="Pt. Ravishankar Shukla University">Pt. Ravishankar Shukla University</option>
            <option value="Pt. Sundarlal Sharma (Open) University">Pt. Sundarlal Sharma (Open) University</option>
            <option value="Sant Gahira Guru Vishwavidyalaya (formerly Sarguja University)">Sant Gahira Guru Vishwavidyalaya (formerly Sarguja University)</option>
            <option value="Shri Rawatpura Sarkar University">Shri Rawatpura Sarkar University</option>
            <option value="Goa University">Goa University</option>
            <option value="Baba Ghulam Shah Badshah University">Baba Ghulam Shah Badshah University</option>
            <option value="Central Institute of Buddhist Studies">Central Institute of Buddhist Studies</option>
            <option value="Central University of Kashmir">Central University of Kashmir</option>
            <option value="Central University of Jammu">Central University of Jammu</option>
            <option value="Cluster University of Jammu">Cluster University of Jammu</option>
            <option value="Cluster University of Srinagar">Cluster University of Srinagar</option>
            <option value="Islamic University of Science">Islamic University of Science</option>
            <option value="Sher-e-Kashmir University">Sher-e-Kashmir University</option>
            <option value="Sher-e-Kashmir University Srinagar">Sher-e-Kashmir University Srinagar</option>
            <option value="Shri Mata Vaishno Devi University">Shri Mata Vaishno Devi University</option>
            <option value="University of Jammu">University of Jammu</option>
            <option value="University of Kashmir">University of Kashmir</option>
            <option value="AISECT University">AISECT University</option>
            <option value="Amity University">Amity University</option>
            <option value="Arka Jain University">Arka Jain University</option>
            <option value="Binod Bihar Mahto Koylanchal University">Binod Bihar Mahto Koylanchal University</option>
            <option value="Birla Institute of Technology">Birla Institute of Technology</option>
            <option value="Birsa Agricultural University">Birsa Agricultural University</option>
            <option value="Capital University">Capital University</option>
            <option value="Central University of Jharkhand">Central University of Jharkhand</option>
            <option value="Dr Shyama Prasad Mukherjee University">Dr Shyama Prasad Mukherjee University</option>
            <option value="Jharkhand Rai University">Jharkhand Rai University</option>
            <option value="Jharkhand University of Technology">Jharkhand University of Technology</option>
            <option value="Kolhan University">Kolhan University</option>
            <option value="Nilamber-Pitamber University">Nilamber-Pitamber University</option>
            <option value="National University of Study & Research in Law">National University of Study & Research in Law</option>
            <option value="Netaji Subhas University">Netaji Subhas University</option>
            <option value="Pragyan International University">Pragyan International University</option>
            <option value="Ram Krishana Dharmarth Foundation University">Ram Krishana Dharmarth Foundation University</option>
            <option value="Cotton College State University">Cotton College State University</option>
            <option value="Ramchandra Chandravansi University">Ramchandra Chandravansi University</option>
            <option value="Ranchi University">Ranchi University</option>
            <option value="Sai Nath University">Sai Nath University</option>
            <option value="Sarla Birla University">Sarla Birla University</option>
            <option value="Sido Kanhu Murmu University">Sido Kanhu Murmu University</option>
            <option value="The Institute of Chartered Financial Analysts of India University">The Institute of Chartered Financial Analysts of India University</option>
            <option value="Usha Martin University">Usha Martin University</option>
            <option value="Vinoba Bhave University">Vinoba Bhave University</option>
            <option value="YBN University">YBN University</option>
            <option value="Adichunchanagiri University">Adichunchanagiri University</option>
            <option value="Alliance University">Alliance University</option>
            <option value="Azim Premji University">Azim Premji University</option>
            <option value="BLDE University">BLDE University</option>
            <option value="Bangalore University">Bangalore University</option>
            <option value="Bengaluru Central University">Bengaluru Central University</option>
            <option value="Bengaluru Dr B.R. Ambedkar School of Economics University">Bengaluru Dr B.R. Ambedkar School of Economics University</option>
            <option value="Bengaluru North University">Bengaluru North University</option>
            <option value="Central University of Karnataka">Central University of Karnataka</option>
            <option value="Christ University">Christ University</option>
            <option value="CMR University">CMR University</option>
            <option value="Davangere University">Davangere University</option>
            <option value="Dayanand Sagar University">Dayanand Sagar University</option>
            <option value="Garden City University">Garden City University</option>
            <option value="Gulbarga University">Gulbarga University</option>
            <option value="Indian Institute of Science">Indian Institute of Science</option>
            <option value="International Institute of Information Technology">International Institute of Information Technology</option>
            <option value="JSS Academy of Higher Education & Research">JSS Academy of Higher Education & Research</option>
            <option value="Jain University">Jain University</option>
            <option value="JSS Science & Technology University">JSS Science & Technology University</option>
            <option value="Jawaharlal Nehru Centre for Advanced Scientific Research">Jawaharlal Nehru Centre for Advanced Scientific Research</option>
            <option value="Karnataka Janapada Vishwavidyalaya">Karnataka Janapada Vishwavidyalaya</option>
            <option value="Kannada University">Kannada University</option>
            <option value="Karnataka State Law University">Karnataka State Law University</option>
            <option value="Karnataka State Open University">Karnataka State Open University</option>
            <option value="Karnataka State Rural Development and Panchayat Raj University">Karnataka State Rural Development and Panchayat Raj University</option>
            <option value="Karnataka State Women University">Karnataka State Women University</option>
            <option value="Karnataka University">Karnataka University</option>
            <option value="Karnataka Veterinary, Animal & Fisheries Science University">Karnataka Veterinary, Animal & Fisheries Science University</option>
            <option value="Karnataka Samskrit University">Karnataka Samskrit University</option>
            <option value="Karnataka Folklore University">Karnataka Folklore University</option>
            <option value="Khaja Bandanawaz University">Khaja Bandanawaz University</option>
            <option value="KLE Academy of Higher Education and Research">KLE Academy of Higher Education and Research</option>
            <option value="KLE Technological University">KLE Technological University</option>
            <option value="KSGH Music and Performing Arts University">KSGH Music and Performing Arts University</option>
            <option value="Kuvempu University">Kuvempu University</option>
            <option value="Mandya University">Mandya University</option>
            <option value="Mangalore University">Mangalore University</option>
            <option value="Manipal Academy of Higher Education">Manipal Academy of Higher Education</option>
            <option value="MS Ramaiah University of Applied Sciences">MS Ramaiah University of Applied Sciences</option>
            <option value="National Law School of India University">National Law School of India University</option>
            <option value="NITTE">NITTE</option>
            <option value="PES University">PES University</option>
            <option value="Presidency University">Presidency University</option>
            <option value="Rai Technology University">Rai Technology University</option>
            <option value="Rajiv Gandhi University of Health Sciences">Rajiv Gandhi University of Health Sciences</option>
            <option value="Rani Channamma University">Rani Channamma University</option>
            <option value="Reva University">Reva University</option>
            <option value="Sharnbasva University">Sharnbasva University</option>
            <option value="Sri Devaraj Urs Academy of Higher Education and Research (SDUAHER)">Sri Devaraj Urs Academy of Higher Education and Research (SDUAHER)</option>
            <option value="Sri Sathya Sai University for Human Excellence">Sri Sathya Sai University for Human Excellence</option>
            <option value="Sri Siddhartha Academy of Higher Education">Sri Siddhartha Academy of Higher Education</option>
            <option value="Srinivas University">Srinivas University</option>
            <option value="Swami Vivekananda Yoga Anusandhana Sansthana (SVYAS)">Swami Vivekananda Yoga Anusandhana Sansthana (SVYAS)</option>
            <option value="Shri Dharmasthala Manjunatheshwara University">Shri Dharmasthala Manjunatheshwara University</option>
            <option value="The University of Trans-Disciplinary Health Sciences and Technology">The University of Trans-Disciplinary Health Sciences and Technology</option>
            <option value="Tumkur University">Tumkur University</option>
            <option value="University of Agricultural Sciences, Bangalore">University of Agricultural Sciences, Bangalore</option>
            <option value="University of Agricultural Sciences, Dharwad">University of Agricultural Sciences, Dharwad</option>
            <option value="University of Agricultural Sciences, Raichur">University of Agricultural Sciences, Raichur</option>
            <option value="University of Horticultural Sciences">University of Horticultural Sciences</option>
            <option value="University of Mysore">University of Mysore</option>
            <option value="Visveswaraiah Technological University (VTU)">Visveswaraiah Technological University (VTU)</option>
            <option value="Vijayanagara Sri Krishnadevaraya University">Vijayanagara Sri Krishnadevaraya University</option>
            <option value="Yenepoya">Yenepoya</option>
            <option value="A.P.J. Abdul Kalam Technological University">A.P.J. Abdul Kalam Technological University</option>
            <option value="Central University of Kerala">Central University of Kerala</option>
            <option value="Chinmaya Vishwavidyapeeth">Chinmaya Vishwavidyapeeth</option>
            <option value="Cochin University of Science & Technology">Cochin University of Science & Technology</option>
            <option value="Indian Institute of Space Science and Technology">Indian Institute of Space Science and Technology</option>
            <option value="Kannur University">Kannur University</option>
            <option value="Kerala Agricultural University">Kerala Agricultural University</option>
            <option value="Kerala Kalamandalam">Kerala Kalamandalam</option>
            <option value="Kerala University of Fisheries & Ocean Studies">Kerala University of Fisheries & Ocean Studies</option>
            <option value="Kerala University of Health Sciences">Kerala University of Health Sciences</option>
            <option value="Kerala Veterinary & Animal Sciences University">Kerala Veterinary & Animal Sciences University</option>
            <option value="Mahatma Gandhi University">Mahatma Gandhi University</option>
            <option value="National University of Advanced Legal Studies (NUALS)">National University of Advanced Legal Studies (NUALS)</option>
            <option value="Shree Sankaracharya University of Sanskrit">Shree Sankaracharya University of Sanskrit</option>
            <option value="Thunchath Ezhuthachan Malayalam University">Thunchath Ezhuthachan Malayalam University</option>
            <option value="University of Calicut">University of Calicut</option>
            <option value="University of Kerala">University of Kerala</option>
            <option value="Panjab University">Panjab University</option>
            <option value="Punjab Engineering College">Punjab Engineering College</option>
            <option value="Amity University">Amity University</option>
            <option value="Ansal University">Ansal University</option>
            <option value="Ashoka University">Ashoka University</option>
            <option value="Bhagat Phool Singh Mahila Vishwavidyalaya">Bhagat Phool Singh Mahila Vishwavidyalaya</option>
            <option value="Baba Mast Nath University">Baba Mast Nath University</option>
            <option value="BML Munjal University">BML Munjal University</option>
            <option value="Al-Falah University">Al-Falah University</option>
            <option value="Radha Govind University">Radha Govind University</option>
            <option value="Central University of Haryana">Central University of Haryana</option>
            <option value="Chaudhary Devi Lal University">Chaudhary Devi Lal University</option>
            <option value="Chaudhary Ranbir Singh University">Chaudhary Ranbir Singh University</option>
            <option value="Chaudhary Charan Singh Haryana Agricultural University">Chaudhary Charan Singh Haryana Agricultural University</option>
            <option value="Deen Bandhu Chhotu Ram University of Science & Technology">Deen Bandhu Chhotu Ram University of Science & Technology</option>
            <option value="Dr BR Ambedkar National Law University (Formerly National Law University Haryana)">Dr BR Ambedkar National Law University (Formerly National Law University Haryana)</option>
            <option value="Apeejay Stya University">Apeejay Stya University</option>
            <option value="GD Goenka University">GD Goenka University</option>
            <option value="Guru Jambeshwar University of Science and Technology">Guru Jambeshwar University of Science and Technology</option>
            <option value="Gurugram University">Gurugram University</option>
            <option value="Haryana Vishwakarma Skill University">Haryana Vishwakarma Skill University</option>
            <option value="IILM University">IILM University</option>
            <option value="Indira Gandhi University">Indira Gandhi University</option>
            <option value="Jagan Nath University">Jagan Nath University</option>
            <option value="K.R. Mangalam University">K.R. Mangalam University</option>
            <option value="Kurukshetra University">Kurukshetra University</option>
            <option value="Lingayas Vidyapeeth">Lingayas Vidyapeeth</option>
            <option value="Lala Lajpat Rai University of Veterinary & Animal Sciences">Lala Lajpat Rai University of Veterinary & Animal Sciences</option>
            <option value="Maharana Pratap Horticultural University">Maharana Pratap Horticultural University</option>
            <option value="Maharishi Balmiki Sanskrit University">Maharishi Balmiki Sanskrit University</option>
            <option value="Maharishi Dayanand University">Maharishi Dayanand University</option>
            <option value="Maharishi Markandeshwar University, Ambala">Maharishi Markandeshwar University, Ambala</option>
            <option value="Manav Rachna International Institute of Research & Studies">Manav Rachna International Institute of Research & Studies</option>
            <option value="M.V.N. University">M.V.N. University</option>
            <option value="National Brain Research Centre">National Brain Research Centre</option>
            <option value="Maharishi Markandeshwar, Mullana">Maharishi Markandeshwar, Mullana</option>
            <option value="National Dairy Research Institute">National Dairy Research Institute</option>
            <option value="National Institute of Food Technology, Entrepreneurship & Management">National Institute of Food Technology, Entrepreneurship & Management</option>
            <option value="(NIFTEM)">(NIFTEM)</option>
            <option value="NIILM University">NIILM University</option>
            <option value="Om Sterling Global University">Om Sterling Global University</option>
            <option value="O.P. Jindal Global University">O.P. Jindal Global University</option>
            <option value="PDM University">PDM University</option>
            <option value="Pt. Bhagwat Dayal Sharma University of Health Sciences">Pt. Bhagwat Dayal Sharma University of Health Sciences</option>
            <option value="Shree Guru Gobind Singh Tricentenary University">Shree Guru Gobind Singh Tricentenary University</option>
            <option value="SRM University">SRM University</option>
            <option value="Starex University">Starex University</option>
            <option value="State University of Performing and Visual Arts">State University of Performing and Visual Arts</option>
            <option value="Manav Rachna University">Manav Rachna University</option>
            <option value="The Northcap University">The Northcap University</option>
            <option value="World University of Design">World University of Design</option>
            <option value="YMCA University of Science & Technology">YMCA University of Science & Technology</option>
            <option value="Dr. B.R. Ambedkar University">Dr. B.R. Ambedkar University</option>
            <option value="Delhi Pharmaceutical Sciences & Research University">Delhi Pharmaceutical Sciences & Research University</option>
            <option value="Delhi Technological University">Delhi Technological University</option>
            <option value="Guru Gobind Singh Indraprastha Vishwavidyalaya">Guru Gobind Singh Indraprastha Vishwavidyalaya</option>
            <option value="Indian Agricultural Research Institute">Indian Agricultural Research Institute</option>
            <option value="Indian Institute of Foreign Trade">Indian Institute of Foreign Trade</option>
            <option value="Indian Law Institute">Indian Law Institute</option>
            <option value="Indira Gandhi National Open University">Indira Gandhi National Open University</option>
            <option value="Indira Gandhi Delhi Technical University for Women">Indira Gandhi Delhi Technical University for Women</option>
            <option value="Indraprastha Institute of Information Technology">Indraprastha Institute of Information Technology</option>
            <option value="Institute of Liver and Biliary Sciences (ILBS)">Institute of Liver and Biliary Sciences (ILBS)</option>
            <option value="Jamia Hamdard">Jamia Hamdard</option>
            <option value="Jamia Millia Islamia University">Jamia Millia Islamia University</option>
            <option value="Jawaharlal Nehru University">Jawaharlal Nehru University</option>
            <option value="National Institute of Educational Planning and Administration">National Institute of Educational Planning and Administration</option>
            <option value="National Law University">National Law University</option>
            <option value="National Museum Institute">National Museum Institute</option>
            <option value="Netaji Subhas University of Technology">Netaji Subhas University of Technology</option>
            <option value="Rashtriya Sanskrit Sansthan">Rashtriya Sanskrit Sansthan</option>
            <option value="Shri Lal Bahadur Shastri Rashtriya Sanskrit Vidyapith">Shri Lal Bahadur Shastri Rashtriya Sanskrit Vidyapith</option>
            <option value="South Asian University">South Asian University</option>
            <option value="TERI School of Advanced Studies">TERI School of Advanced Studies</option>
            <option value="University of Delhi">University of Delhi</option>
            <option value="Amity University">Amity University</option>
            <option value="Aryabhatta knowledge University">Aryabhatta knowledge University</option>
            <option value="Babasaheb Bhimrao Ambedkar Bihar University">Babasaheb Bhimrao Ambedkar Bihar University</option>
            <option value="Bhupendra Narayan Mandal University">Bhupendra Narayan Mandal University</option>
            <option value="Bihar Agricultural University">Bihar Agricultural University</option>
            <option value="Bihar Animal Sciences University">Bihar Animal Sciences University</option>
            <option value="Central University of South Bihar">Central University of South Bihar</option>
            <option value="Chanakya National Law University">Chanakya National Law University</option>
            <option value="Dr C.V. Raman University">Dr C.V. Raman University</option>
            <option value="Gopal Narayan Singh University">Gopal Narayan Singh University</option>
            <option value="Jai Prakash Vishwavidyalaya">Jai Prakash Vishwavidyalaya</option>
            <option value="Kameshwara Singh Darbhanga Sanskrit Vishwavidyalaya">Kameshwara Singh Darbhanga Sanskrit Vishwavidyalaya</option>
            <option value="K.K. University">K.K. University</option>
            <option value="Lalit Narayan Mithila University">Lalit Narayan Mithila University</option>
            <option value="Magadh University">Magadh University</option>
            <option value="Mahatma Gandhi Central University">Mahatma Gandhi Central University</option>
            <option value="Mata Gujri University">Mata Gujri University</option>
            <option value="Maulana Mazharul Haque Arabic & Persian University">Maulana Mazharul Haque Arabic & Persian University</option>
            <option value="Munger University">Munger University</option>
            <option value="Nalanda University">Nalanda University</option>
            <option value="Nalanda Open University">Nalanda Open University</option>
            <option value="Nava Nalanda Mahavihara">Nava Nalanda Mahavihara</option>
            <option value="Patna University">Patna University</option>
            <option value="Patliputra University">Patliputra University</option>
            <option value="Purnea University">Purnea University</option>
            <option value="Rajendra Agricultural University">Rajendra Agricultural University</option>
            <option value="Sandip University">Sandip University</option>
            <option value="T.M. University">T.M. University</option>
            <option value="Veer Kunwar Singh University">Veer Kunwar Singh University</option>
            <option value="Al-Karim University">Al-Karim University</option>
            <option value="Ahmedabad University">Ahmedabad University</option>
            <option value="Anand Agricultural University">Anand Agricultural University</option>
            <option value="Anant National University">Anant National University</option>
            <option value="Atmiya University">Atmiya University</option>
            <option value="AURO University of Hospitality and Management">AURO University of Hospitality and Management</option>
            <option value="Bhaikaka University">Bhaikaka University</option>
            <option value="Bhakta Kavi Narsinh Mehta University">Bhakta Kavi Narsinh Mehta University</option>
            <option value="Birsa Munda Tribal University">Birsa Munda Tribal University</option>
            <option value="Calorx Teacher’s University">Calorx Teacher’s University</option>
            <option value="Centre for Environmental Planning and Technology University (CEPT)">Centre for Environmental Planning and Technology University (CEPT)</option>
            <option value="Charotar University of Science & Technology">Charotar University of Science & Technology</option>
            <option value="Children’s University">Children’s University</option>
            <option value="CU Shah University">CU Shah University</option>
            <option value="Dharmsinh Desai University">Dharmsinh Desai University</option>
            <option value="Dhirubhai Ambani Institute of Information and Communication Technology (DAIICT)">Dhirubhai Ambani Institute of Information and Communication Technology (DAIICT)</option>
            <option value="Dr. Babasaheb Ambedkar Open University">Dr. Babasaheb Ambedkar Open University</option>
            <option value="Ganpat University">Ganpat University</option>
            <option value="GLS University">GLS University</option>
            <option value="Gokul Global University">Gokul Global University</option>
            <option value="Central University of Gujarat">Central University of Gujarat</option>
            <option value="GSFC University">GSFC University</option>
            <option value="Chaudhary Bansi Lal University">Chaudhary Bansi Lal University</option>
            <option value="Gujarat Biotechnology University">Gujarat Biotechnology University</option>
            <option value="Gujarat National Law University">Gujarat National Law University</option>
            <option value="Gujarat Technological University">Gujarat Technological University</option>
            <option value="Gujarat University of Transplantation Sciences(GUTS)">Gujarat University of Transplantation Sciences(GUTS)</option>
            <option value="Gujarat Maritime University">Gujarat Maritime University</option>
            <option value="Gujarat Vidyapith">Gujarat Vidyapith</option>
            <option value="Gujarat Forensic Sciences University">Gujarat Forensic Sciences University</option>
            <option value="Hemchandracharya North Gujarat University">Hemchandracharya North Gujarat University</option>
            <option value="Indian Institute of Public Health(IIPH)">Indian Institute of Public Health(IIPH)</option>
            <option value="Indian Institute of Teacher Education">Indian Institute of Teacher Education</option>
            <option value="Indrashil University">Indrashil University</option>
            <option value="Indus University">Indus University</option>
            <option value="Institute of Infrastructure Technology Research and Management (IITRAM)">Institute of Infrastructure Technology Research and Management (IITRAM)</option>
            <option value="Gujarat Ayurveda University">Gujarat Ayurveda University</option>
            <option value="Institute of Advanced Research (IAR)">Institute of Advanced Research (IAR)</option>
            <option value="ITM-Vocational University">ITM-Vocational University</option>
            <option value="Junagarh Agricultural University">Junagarh Agricultural University</option>
            <option value="Kadi Sarva Vishwavidyalaya">Kadi Sarva Vishwavidyalaya</option>
            <option value="Kamdhenu University">Kamdhenu University</option>
            <option value="Karnavati University">Karnavati University</option>
            <option value="Krantiguru Shyamji Krishna Verma Kachchh University">Krantiguru Shyamji Krishna Verma Kachchh University</option>
            <option value="Lakulish Yoga University">Lakulish Yoga University</option>
            <option value="Maharaja Krishna Kumar Singh Ji Bhavnagar University">Maharaja Krishna Kumar Singh Ji Bhavnagar University</option>
            <option value="Maharaja Sayajirao University of Baroda">Maharaja Sayajirao University of Baroda</option>
            <option value="Marwadi University">Marwadi University</option>
            <option value="National Rail and Transportation Institute (NRTI)">National Rail and Transportation Institute (NRTI)</option>
            <option value="Navsari Agricultural University">Navsari Agricultural University</option>
            <option value="Nirma University">Nirma University</option>
            <option value="Navrachana University">Navrachana University</option>
            <option value="Pandit Deendayal Petroleum University">Pandit Deendayal Petroleum University</option>
            <option value="Parul University">Parul University</option>
            <option value="Plastindia International University">Plastindia International University</option>
            <option value="PP Savani University">PP Savani University</option>
            <option value="Raksha Shakti University">Raksha Shakti University</option>
            <option value="RK University">RK University</option>
            <option value="Rai University">Rai University</option>
            <option value="Sankalchand Patel University">Sankalchand Patel University</option>
            <option value="Sardar Krushinagar Dantiwada Agricultural University">Sardar Krushinagar Dantiwada Agricultural University</option>
            <option value="Sardar Patel University">Sardar Patel University</option>
            <option value="Saurashtra University">Saurashtra University</option>
            <option value="Shree Somnath Sanskrit University">Shree Somnath Sanskrit University</option>
            <option value="Shreyarth University">Shreyarth University</option>
            <option value="Shri Govind Guru University">Shri Govind Guru University</option>
            <option value="Silver Oak University">Silver Oak University</option>
            <option value="Sumandeep Vidyapeeth">Sumandeep Vidyapeeth</option>
            <option value="Swarnim Gujarat Sports University">Swarnim Gujarat Sports University</option>
            <option value="Swarnim Startup & Innovation University">Swarnim Startup & Innovation University</option>
            <option value="Team Lease Skills University">Team Lease Skills University</option>
            <option value="UKA Tarsadia University">UKA Tarsadia University</option>
            <option value="Veer Narmad South Gujarat University">Veer Narmad South Gujarat University</option>
            <option value="Central Agricultural University">Central Agricultural University</option>
            <option value="Dhanamanjuri University">Dhanamanjuri University</option>
            <option value="Manipur International University">Manipur International University</option>
            <option value="Manipur University">Manipur University</option>
            <option value="Manipur Technical University">Manipur Technical University</option>
            <option value="Manipur University of Culture">Manipur University of Culture</option>
            <option value="National Sports University">National Sports University</option>
            <option value="Sangai International University">Sangai International University</option>
            <option value="CMJ University">CMJ University</option>
            <option value="Martin Luther Christian University">Martin Luther Christian University</option>
            <option value="Mahatma Gandhi University">Mahatma Gandhi University</option>
            <option value="North-Eastern Hill University">North-Eastern Hill University</option>
            <option value="Techno Global University">Techno Global University</option>
            <option value="The Institute of Chartered Financial Analysts of India University">The Institute of Chartered Financial Analysts of India University</option>
            <option value="University of Science & Technology">University of Science & Technology</option>
            <option value="University of Technology & Management">University of Technology & Management</option>
            <option value="William Carey University">William Carey University</option>
            <option value="Mizoram University">Mizoram University</option>
            <option value="The Institute of Chartered Financial Analysts of India University">The Institute of Chartered Financial Analysts of India University</option>
            <option value="AKS University">AKS University</option>
            <option value="Atal Bihari Vajpayee Hindi Vishwavidyalaya">Atal Bihari Vajpayee Hindi Vishwavidyalaya</option>
            <option value="Avantika University">Avantika University</option>
            <option value="Awadhesh Pratap Singh University">Awadhesh Pratap Singh University</option>
            <option value="Amity University">Amity University</option>
            <option value="Barkatullah University">Barkatullah University</option>
            <option value="Bhabha University">Bhabha University</option>
            <option value="Devi Ahilya Vishwavidyalaya">Devi Ahilya Vishwavidyalaya</option>
            <option value="Dharmashastra National Law University">Dharmashastra National Law University</option>
            <option value="Dr A.P.J. Abdul Kalam University">Dr A.P.J. Abdul Kalam University</option>
            <option value="Dr B.R. Ambedkar University of Social Sciences">Dr B.R. Ambedkar University of Social Sciences</option>
            <option value="Dr C.V. Raman University">Dr C.V. Raman University</option>
            <option value="Dr Harisingh Gour Vishwavidyalaya">Dr Harisingh Gour Vishwavidyalaya</option>
            <option value="G.H. Raisoni University">G.H. Raisoni University</option>
            <option value="I.E.S University">I.E.S University</option>
            <option value="ITM University">ITM University</option>
            <option value="Jagran Lakecity University">Jagran Lakecity University</option>
            <option value="Jawaharlal Nehru Krishi Vishwavidyalaya">Jawaharlal Nehru Krishi Vishwavidyalaya</option>
            <option value="Jaypee University of Engineering & Technology">Jaypee University of Engineering & Technology</option>
            <option value="Jiwaji University">Jiwaji University</option>
            <option value="Lakshmibai National Institute of Physical Education">Lakshmibai National Institute of Physical Education</option>
            <option value="LNCT University">LNCT University</option>
            <option value="Madhya Pradesh Medical Science University">Madhya Pradesh Medical Science University</option>
            <option value="Madhyanchal Professional University">Madhyanchal Professional University</option>
            <option value="Maharaja Chhatrasal Bundelkhand Vishwavidyalaya">Maharaja Chhatrasal Bundelkhand Vishwavidyalaya</option>
            <option value="Mahatma Gandhi Chitrakoot Gramoday Vishwavidyalaya">Mahatma Gandhi Chitrakoot Gramoday Vishwavidyalaya</option>
            <option value="M.P.Bhoj (open) University">M.P.Bhoj (open) University</option>
            <option value="Maharishi Mahesh Yogi Vedic Vishwavidyalaya">Maharishi Mahesh Yogi Vedic Vishwavidyalaya</option>
            <option value="Maharshi Panini Sanskrit Evam Vedic Vishwavidyalaya">Maharshi Panini Sanskrit Evam Vedic Vishwavidyalaya</option>
            <option value="Makhanlal Chaturvedi Rashtriya Patrakarita National University of Journalism">Makhanlal Chaturvedi Rashtriya Patrakarita National University of Journalism</option>
            <option value="Malwanchal University">Malwanchal University</option>
            <option value="Mandsaur University">Mandsaur University</option>
            <option value="Mangalayatan University">Mangalayatan University</option>
            <option value="Mansarovar Global University">Mansarovar Global University</option>
            <option value="Medi-Caps University">Medi-Caps University</option>
            <option value="Nanaji Deshmukh Pashu Chikitsa Vigyan Vishwavidyalaya">Nanaji Deshmukh Pashu Chikitsa Vigyan Vishwavidyalaya</option>
            <option value="National Law Institute University">National Law Institute University</option>
            <option value="Oriental University">Oriental University</option>
            <option value="Pandit S.N. Shukla University">Pandit S.N. Shukla University</option>
            <option value="People’s University">People’s University</option>
            <option value="P.K. University">P.K. University</option>
            <option value="Raja Mansingh Tomar Music & Arts University">Raja Mansingh Tomar Music & Arts University</option>
            <option value="Rajiv Gandhi Proudyogiki Vishwavidyalaya">Rajiv Gandhi Proudyogiki Vishwavidyalaya</option>
            <option value="Rani Durgavati Vishwavidyalaya">Rani Durgavati Vishwavidyalaya</option>
            <option value="RKDF University">RKDF University</option>
            <option value="Rajmata Vijayaraje Scindia Krishi Vishwavidyalaya">Rajmata Vijayaraje Scindia Krishi Vishwavidyalaya</option>
            <option value="Rabindranath Tagore University (Formerly AISECT University)">Rabindranath Tagore University (Formerly AISECT University)</option>
            <option value="Renaissance University">Renaissance University</option>
            <option value="Sage University">Sage University</option>
            <option value="Sanchi University of Buddhist-Indic Studies">Sanchi University of Buddhist-Indic Studies</option>
            <option value="Sardar Patel University">Sardar Patel University</option>
            <option value="Sarvepalli Radhakrishnan University">Sarvepalli Radhakrishnan University</option>
            <option value="Shri Krishna University">Shri Krishna University</option>
            <option value="Shri Vaishnav Vidyapeeth Vishwavidyalaya">Shri Vaishnav Vidyapeeth Vishwavidyalaya</option>
            <option value="Swami Vivekanand University">Swami Vivekanand University</option>
            <option value="Symbiosis University of Applied Sciences">Symbiosis University of Applied Sciences</option>
            <option value="Techno Global University">Techno Global University</option>
            <option value="Gujarat University">Gujarat University</option>
            <option value="The Indira Gandhi National Tribal University">The Indira Gandhi National Tribal University</option>
            <option value="Vikram University">Vikram University</option>
            <option value="VIT Bhopal University">VIT Bhopal University</option>
            <option value="Nagaland University">Nagaland University</option>
            <option value="St. Joseph University">St. Joseph University</option>
            <option value="The Global Open University">The Global Open University</option>
            <option value="ICFAI University">ICFAI University</option>
            <option value="Pondicherry University">Pondicherry University</option>
            <option value="Sri Balaji Vidyapeeth">Sri Balaji Vidyapeeth</option>
            <option value="Akal University">Akal University</option>
            <option value="Baba Farid University of Health Sciences">Baba Farid University of Health Sciences</option>
            <option value="Chandigarh University">Chandigarh University</option>
            <option value="Adesh University">Adesh University</option>
            <option value="Sri Satya Sai University of Technology & Medical Sciences">Sri Satya Sai University of Technology & Medical Sciences</option>
            <option value="Chitkara University">Chitkara University</option>
            <option value="CT University">CT University</option>
            <option value="D.A.V University">D.A.V University</option>
            <option value="Desh Bhagat University">Desh Bhagat University</option>
            <option value="GNA University">GNA University</option>
            <option value="Guru Angad Dev Veterinary & Animal Sciences University">Guru Angad Dev Veterinary & Animal Sciences University</option>
            <option value="Guru Kashi University">Guru Kashi University</option>
            <option value="Guru Nanak Dev University">Guru Nanak Dev University</option>
            <option value="Guru Ravidas Ayurved University">Guru Ravidas Ayurved University</option>
            <option value="Lovely Professional University">Lovely Professional University</option>
            <option value="Maharaja Ranjit Singh Punjab Technical University">Maharaja Ranjit Singh Punjab Technical University</option>
            <option value="Punjabi University">Punjabi University</option>
            <option value="Rayat Bahra University">Rayat Bahra University</option>
            <option value="RIMT University">RIMT University</option>
            <option value="Central University of Punjab">Central University of Punjab</option>
            <option value="Sant Baba Bhag Singh University">Sant Baba Bhag Singh University</option>
            <option value="Sant Longowal Institute of Engineering and Technology (SLIET)">Sant Longowal Institute of Engineering and Technology (SLIET)</option>
            <option value="Sri Guru Granth Sahib World University">Sri Guru Granth Sahib World University</option>
            <option value="Sri Guru Ram Das University of Health Sciences">Sri Guru Ram Das University of Health Sciences</option>
            <option value="Thapar Institute of Engineering & Technology">Thapar Institute of Engineering & Technology</option>
            <option value="The I.K. Gujaral Punjab Technical University">The I.K. Gujaral Punjab Technical University</option>
            <option value="The Maharaja Bhupinder Singh Punjab Sports University">The Maharaja Bhupinder Singh Punjab Sports University</option>
            <option value="The Rajiv Gandhi National University of Law">The Rajiv Gandhi National University of Law</option>
            <option value="Sikkim Manipal University">Sikkim Manipal University</option>
            <option value="Sikkim State University">Sikkim State University</option>
            <option value="Sikkim University">Sikkim University</option>
            <option value="Shri Ramasamy Memorial University">Shri Ramasamy Memorial University</option>
            <option value="The Institute of Chartered Financial Analysts of India University">The Institute of Chartered Financial Analysts of India University</option>
            <option value="Punjab Agricultural University">Punjab Agricultural University</option>
            <option value="Academy of Maritime Education and Training">Academy of Maritime Education and Training</option>
            <option value="Alagappa University">Alagappa University</option>
            <option value="Amrita Vishwa Vidyapeetham">Amrita Vishwa Vidyapeetham</option>
            <option value="Anna University">Anna University</option>
            <option value="Annamalai University">Annamalai University</option>
            <option value="Avinashilingam Institute for Home Science & Higher Education for Women">Avinashilingam Institute for Home Science & Higher Education for Women</option>
            <option value="B.S. Abdur Rahman Crescent Institute of Science and Technology">B.S. Abdur Rahman Crescent Institute of Science and Technology</option>
            <option value="Bharath Institute of Higher Education & Research">Bharath Institute of Higher Education & Research</option>
            <option value="Bharathidasan University">Bharathidasan University</option>
            <option value="Central University of Tamil Nadu">Central University of Tamil Nadu</option>
            <option value="Chennai Mathematical Institute">Chennai Mathematical Institute</option>
            <option value="Chettinad Academy of Research and Education (CARE)">Chettinad Academy of Research and Education (CARE)</option>
            <option value="Dr M.G.R. Educational and Research Institute">Dr M.G.R. Educational and Research Institute</option>
            <option value="Gandhigram Rural Institute">Gandhigram Rural Institute</option>
            <option value="Hindustan Institute of Technology and Science (HITS)">Hindustan Institute of Technology and Science (HITS)</option>
            <option value="Kalasalingam Academy of Research and Education">Kalasalingam Academy of Research and Education</option>
            <option value="Karpagam Academy of Higher Education">Karpagam Academy of Higher Education</option>
            <option value="Karunya Institute of Technology and Sciences">Karunya Institute of Technology and Sciences</option>
            <option value="Rajiv Gandhi University">Rajiv Gandhi University</option>
            <option value="Madurai Kamraj University">Madurai Kamraj University</option>
            <option value="Manonmaniam Sundarnar University">Manonmaniam Sundarnar University</option>
            <option value="Bharathiar University">Bharathiar University</option>
            <option value="Meenakshi Academy of Higher Education and Research">Meenakshi Academy of Higher Education and Research</option>
            <option value="Mother Teresa Womens University">Mother Teresa Womens University</option>
            <option value="Noorul Islam Centre for Higher Education">Noorul Islam Centre for Higher Education</option>
            <option value="Periyar Maniammai Institute of Science & Technology (PMIST)">Periyar Maniammai Institute of Science & Technology (PMIST)</option>
            <option value="Periyar University">Periyar University</option>
            <option value="Ponnaiyah Ramajayam Institute of Science & Technology (PRIST)">Ponnaiyah Ramajayam Institute of Science & Technology (PRIST)</option>
            <option value="S.R.M. Institute of Sciences and Technology">S.R.M. Institute of Sciences and Technology</option>
            <option value="Sathyabama Institute of Science and Technology">Sathyabama Institute of Science and Technology</option>
            <option value="Saveetha Institute of Medical and Technical Sciences">Saveetha Institute of Medical and Technical Sciences</option>
            <option value="Shanmugha Arts, Science, Technology and Research Academy (SASTRA)">Shanmugha Arts, Science, Technology and Research Academy (SASTRA)</option>
            <option value="Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya University (SCSVMV)">Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya University (SCSVMV)</option>
            <option value="Sri Ramachandra Medical College and Research Institute">Sri Ramachandra Medical College and Research Institute</option>
            <option value="St. Peters Institute of Higher Education and Research">St. Peters Institute of Higher Education and Research</option>
            <option value="Tamil Nadu Teacher Education University">Tamil Nadu Teacher Education University</option>
            <option value="Tamil University">Tamil University</option>
            <option value="Tamil Nadu Agricultural University">Tamil Nadu Agricultural University</option>
            <option value="Tamil Nadu Dr Ambedkar Law University">Tamil Nadu Dr Ambedkar Law University</option>
            <option value="Tamil Nadu Dr M.G.R. Medical University">Tamil Nadu Dr M.G.R. Medical University</option>
            <option value="Tamil Nadu Fisheries University">Tamil Nadu Fisheries University</option>
            <option value="Tamil Nadu Music and Fine Arts University">Tamil Nadu Music and Fine Arts University</option>
            <option value="Tamil Nadu National Law School">Tamil Nadu National Law School</option>
            <option value="Tamil Nadu Open University">Tamil Nadu Open University</option>
            <option value="Tamil Nadu Physical Education and Sports University">Tamil Nadu Physical Education and Sports University</option>
            <option value="Tamil Nadu Veterinary & Animal Sciences University">Tamil Nadu Veterinary & Animal Sciences University</option>
            <option value="Thiruvalluvar University">Thiruvalluvar University</option>
            <option value="University of Madras">University of Madras</option>
            <option value="Vel Tech Rangarajan Dr Sagunthala R&D Institute of Science and Technology">Vel Tech Rangarajan Dr Sagunthala R&D Institute of Science and Technology</option>
            <option value="Vels Institute of Science, Technology & Advanced Studies (VISTAS)">Vels Institute of Science, Technology & Advanced Studies (VISTAS)</option>
            <option value="Vellore Institute of Technology">Vellore Institute of Technology</option>
            <option value="Vinayaka Missions Research Foundation">Vinayaka Missions Research Foundation</option>
            <option value="Acharya NG Ranga Agricultural University">Acharya NG Ranga Agricultural University</option>
            <option value="Maharaja Bir Bikram University">Maharaja Bir Bikram University</option>
            <option value="Tripura University">Tripura University</option>
            <option value="AIPH University">AIPH University</option>
            <option value="ASBM University">ASBM University</option>
            <option value="Berhampur University">Berhampur University</option>
            <option value="Biju Patnaik University of Technology">Biju Patnaik University of Technology</option>
            <option value="Birla Global University">Birla Global University</option>
            <option value="Centurion University of Technology and Management">Centurion University of Technology and Management</option>
            <option value="Fakir Mohan University">Fakir Mohan University</option>
            <option value="Gandhi Institute of Engineering & Technology University">Gandhi Institute of Engineering & Technology University</option>
            <option value="Gangadhar Meher University">Gangadhar Meher University</option>
            <option value="Vinayaka Missions Sikkim University">Vinayaka Missions Sikkim University</option>
            <option value="International Institute of Information Technology">International Institute of Information Technology</option>
            <option value="Kalinga Institute of Industrial Technology">Kalinga Institute of Industrial Technology</option>
            <option value="Kalinga Institute of Social Sciences">Kalinga Institute of Social Sciences</option>
            <option value="Khallikote University">Khallikote University</option>
            <option value="National law University">National law University</option>
            <option value="North Orissa University">North Orissa University</option>
            <option value="Odisha State Open University">Odisha State Open University</option>
            <option value="Orissa University of Agriculture & Technology">Orissa University of Agriculture & Technology</option>
            <option value="Rama Devi Women’s University">Rama Devi Women’s University</option>
            <option value="Ravenshaw University">Ravenshaw University</option>
            <option value="Sambalpur University">Sambalpur University</option>
            <option value="Shiksha O Anusandhan">Shiksha O Anusandhan</option>
            <option value="Sri Sri University">Sri Sri University</option>
            <option value="Central University of Orissa">Central University of Orissa</option>
            <option value="Utkal University">Utkal University</option>
            <option value="Utkal University of Culture">Utkal University of Culture</option>
            <option value="Veer Surendra Sai Institute of Medical Sciences and Research">Veer Surendra Sai Institute of Medical Sciences and Research</option>
            <option value="Veer Surendra Sai University of Technology">Veer Surendra Sai University of Technology</option>
            <option value="Shri Jagannath Sanskrit Vishwavidyalaya">Shri Jagannath Sanskrit Vishwavidyalaya</option>
            <option value="Xavier University">Xavier University</option>
            <option value="Chaitanya Institute of Science & Technology">Chaitanya Institute of Science & Technology</option>
            <option value="ICFAI Foundation for Higher Education">ICFAI Foundation for Higher Education</option>
            <option value="International Institute of Information Technology">International Institute of Information Technology</option>
            <option value="Jawaharlal Nehru Architecture and Fine Arts University">Jawaharlal Nehru Architecture and Fine Arts University</option>
            <option value="Jawaharlal Nehru Technological University">Jawaharlal Nehru Technological University</option>
            <option value="Kakatiya University">Kakatiya University</option>
            <option value="Kaloji Narayan Rao University of Health Sciences">Kaloji Narayan Rao University of Health Sciences</option>
            <option value="Mahatma Gandhi University">Mahatma Gandhi University</option>
            <option value="Maulana Azad National Urdu University">Maulana Azad National Urdu University</option>
            <option value="NALSAR University of Law, Justice, Shameerpet">NALSAR University of Law, Justice, Shameerpet</option>
            <option value="Nizams Institute of Medical Sciences">Nizams Institute of Medical Sciences</option>
            <option value="Osmania University">Osmania University</option>
            <option value="Palamuru University">Palamuru University</option>
            <option value="Potti Sreeramulu Telugu University">Potti Sreeramulu Telugu University</option>
            <option value="Jayashankar Telangana State Agricultural University">Jayashankar Telangana State Agricultural University</option>
            <option value="Satavahana University">Satavahana University</option>
            <option value="Sri Konda Laxman Telangana">Sri Konda Laxman Telangana</option>
            <option value="Dr B.R. Ambedkar Open University">Dr B.R. Ambedkar Open University</option>
            <option value="Sri P.V. Narsimha Rao Telangana Veterinary University">Sri P.V. Narsimha Rao Telangana Veterinary University</option>
            <option value="Telangana University, Dichpally">Telangana University, Dichpally</option>
            <option value="The English and Foreign Languages University">The English and Foreign Languages University</option>
            <option value="University of Hyderabad">University of Hyderabad</option>
            <option value="Rajiv Gandhi University of Knowledge Technologies">Rajiv Gandhi University of Knowledge Technologies</option>
            <option value="Aligarh Muslim University">Aligarh Muslim University</option>
            <option value="Amity University">Amity University</option>
            <option value="Babasaheb Bhimrao Ambedkar University">Babasaheb Bhimrao Ambedkar University</option>
            <option value="Banaras Hindu University">Banaras Hindu University</option>
            <option value="Banda University of Agriculture & Technology">Banda University of Agriculture & Technology</option>
            <option value="Bareilly International University">Bareilly International University</option>
            <option value="Bennett University">Bennett University</option>
            <option value="Bhatkhande Music Institute">Bhatkhande Music Institute</option>
            <option value="Bundelkhand University">Bundelkhand University</option>
            <option value="Babu Banarasi Das University">Babu Banarasi Das University</option>
            <option value="Central Institute of Higher Tibetan Studies">Central Institute of Higher Tibetan Studies</option>
            <option value="Chandra Shekhar Azad University">Chandra Shekhar Azad University</option>
            <option value="Chatrapati Shahuji Maharaj Kanpur University">Chatrapati Shahuji Maharaj Kanpur University</option>
            <option value="CCS University">CCS University</option>
            <option value="Dayalbagh Educational Institute">Dayalbagh Educational Institute</option>
            <option value="Deen Dayal Upadhyay Gorakhpur University">Deen Dayal Upadhyay Gorakhpur University</option>
            <option value="Dr A.P.J. Abdul Kalam Technical University">Dr A.P.J. Abdul Kalam Technical University</option>
            <option value="Dr Ram Manohar Lohia Awadh University">Dr Ram Manohar Lohia Awadh University</option>
            <option value="Dr Ram Manohar Lohia Institute of Medical Sciences">Dr Ram Manohar Lohia Institute of Medical Sciences</option>
            <option value="Dr. B.R. Ambedkar University">Dr. B.R. Ambedkar University</option>
            <option value="Dr Ram Manohar Lohiya National Law University">Dr Ram Manohar Lohiya National Law University</option>
            <option value="Era University">Era University</option>
            <option value="GLA University">GLA University</option>
            <option value="Galgotias University">Galgotias University</option>
            <option value="Gautam Buddha University">Gautam Buddha University</option>
            <option value="Harcourt Butler Technical University">Harcourt Butler Technical University</option>
            <option value="IIMT University">IIMT University</option>
            <option value="Indian Veterinary Research Institute">Indian Veterinary Research Institute</option>
            <option value="IFTM University">IFTM University</option>
            <option value="Invertis University">Invertis University</option>
            <option value="Integral University">Integral University</option>
            <option value="Jagadguru Rambhadracharya Handicapped University">Jagadguru Rambhadracharya Handicapped University</option>
            <option value="Jan Nayak Chandrashekhar University">Jan Nayak Chandrashekhar University</option>
            <option value="Jaypee Institute of Information Technology">Jaypee Institute of Information Technology</option>
            <option value="Jaypee University">Jaypee University</option>
            <option value="J.S. University">J.S. University</option>
            <option value="Khwaja Moinuddin Chishti Urdu, Arabi~Farsi University">Khwaja Moinuddin Chishti Urdu, Arabi~Farsi University</option>
            <option value="King George Medical University">King George Medical University</option>
            <option value="Madan Mohan Malaviya University of Technology">Madan Mohan Malaviya University of Technology</option>
            <option value="M.J.P.Rohilkhand University">M.J.P.Rohilkhand University</option>
            <option value="Mahatma Gandhi Kashi Vidyapeeth">Mahatma Gandhi Kashi Vidyapeeth</option>
            <option value="Maharishi University of Information Technology">Maharishi University of Information Technology</option>
            <option value="Mangalayatan University">Mangalayatan University</option>
            <option value="Mohammad Ali Jauhar University">Mohammad Ali Jauhar University</option>
            <option value="Monad University">Monad University</option>
            <option value="Narendra Deo University of Agriculture & Technology">Narendra Deo University of Agriculture & Technology</option>
            <option value="Nehru Gram Bharati">Nehru Gram Bharati</option>
            <option value="Noida International University">Noida International University</option>
            <option value="Rajiv Gandhi National Aviation University">Rajiv Gandhi National Aviation University</option>
            <option value="Rama University">Rama University</option>
            <option value="Rani Lakshmi Bai Central Agricultural University">Rani Lakshmi Bai Central Agricultural University</option>
            <option value="Sam Higginbottom Institute of Agriculture">Sam Higginbottom Institute of Agriculture</option>
            <option value="Sampurnanand Sanskrit Vishwavidyalaya">Sampurnanand Sanskrit Vishwavidyalaya</option>
            <option value="Sanskriti University">Sanskriti University</option>
            <option value="Santosh University">Santosh University</option>
            <option value="Sardar Vallabh Bhai Patel University">Sardar Vallabh Bhai Patel University</option>
            <option value="Sharda University">Sharda University</option>
            <option value="Shiv Nadar University">Shiv Nadar University</option>
            <option value="Shobhit Institute of Engineering & Technology">Shobhit Institute of Engineering & Technology</option>
            <option value="Shobhit University">Shobhit University</option>
            <option value="Shri Ramswaroop Memorial University">Shri Ramswaroop Memorial University</option>
            <option value="Siddharth University">Siddharth University</option>
            <option value="Swami Vivekanand Subharti University">Swami Vivekanand Subharti University</option>
            <option value="Shri Venkateshwara University">Shri Venkateshwara University</option>
            <option value="Teerthanker Mahaveer University">Teerthanker Mahaveer University</option>
            <option value="The Glocal University">The Glocal University</option>
            <option value="University of Lucknow">University of Lucknow</option>
            <option value="King Georges Medical University">King Georges Medical University</option>
            <option value="Uttar Pradesh Pandit Deen Dayal Upadhyaya">Uttar Pradesh Pandit Deen Dayal Upadhyaya</option>
            <option value="U.P. Rajarshi Tandon Open University">U.P. Rajarshi Tandon Open University</option>
            <option value="Uttar Pradesh Viklang Uddhar">Uttar Pradesh Viklang Uddhar</option>
            <option value="Uttar Pradesh University of Medical Sciences">Uttar Pradesh University of Medical Sciences</option>
            <option value="University of Allahabad">University of Allahabad</option>
            <option value="Veer Bahadur Singh Purvanchal University">Veer Bahadur Singh Purvanchal University</option>
            <option value="Allahabad State University">Allahabad State University</option>
            <option value="Adamas University">Adamas University</option>
            <option value="Amity University">Amity University</option>
            <option value="Bankura University">Bankura University</option>
            <option value="Bidhan Chandra Krishi Vishwavidyalaya">Bidhan Chandra Krishi Vishwavidyalaya</option>
            <option value="Brainware University">Brainware University</option>
            <option value="Cooch Behar Panchanan Barma University">Cooch Behar Panchanan Barma University</option>
            <option value="Diamond Harbour Womens University">Diamond Harbour Womens University</option>
            <option value="Indian Association for the Cultivation of Science (IACS)">Indian Association for the Cultivation of Science (IACS)</option>
            <option value="Jadavpur University">Jadavpur University</option>
            <option value="JIS University">JIS University</option>
            <option value="Kazi Nazrul University">Kazi Nazrul University</option>
            <option value="Maulana Abul Kalam Azad University of Technology">Maulana Abul Kalam Azad University of Technology</option>
            <option value="Netaji Subhash Open University">Netaji Subhash Open University</option>
            <option value="Presidency University">Presidency University</option>
            <option value="Rabindra Bharati University">Rabindra Bharati University</option>
            <option value="Raiganj University">Raiganj University</option>
            <option value="Ramakrishna Mission Vivekananda Educational and Research Institute">Ramakrishna Mission Vivekananda Educational and Research Institute</option>
            <option value="Seacom Skills University">Seacom Skills University</option>
            <option value="Sidho-Kanho-Birsha University">Sidho-Kanho-Birsha University</option>
            <option value="Sister Nivedita University">Sister Nivedita University</option>
            <option value="St. Xaviers University">St. Xaviers University</option>
            <option value="Techno India University">Techno India University</option>
            <option value="The Neotia University">The Neotia University</option>
            <option value="The Sanskrit College and University">The Sanskrit College and University</option>
            <option value="The West Bengal National University of Juridical Science">The West Bengal National University of Juridical Science</option>
            <option value="The West Bengal University of Health Sciences">The West Bengal University of Health Sciences</option>
            <option value="The West Bengal University of Teachers Training, Education Planning">The West Bengal University of Teachers Training, Education Planning</option>
            <option value="and Administration">and Administration</option>
            <option value="University of Burdwan">University of Burdwan</option>
            <option value="University of Calcutta">University of Calcutta</option>
            <option value="University of Engineering and Management">University of Engineering and Management</option>
            <option value="University of Gour Banga">University of Gour Banga</option>
            <option value="University of Kalyani">University of Kalyani</option>
            <option value="University of North Bengal">University of North Bengal</option>
            <option value="Uttar Banga Krishi Vishwavidyalaya">Uttar Banga Krishi Vishwavidyalaya</option>
            <option value="Vidyasagar University">Vidyasagar University</option>
            <option value="Visva Bharati University">Visva Bharati University</option>
            <option value="West Bengal State University">West Bengal State University</option>
            <option value="West Bengal University of Animal">West Bengal University of Animal</option>
            <option value="Indian Maritime University">Indian Maritime University</option>
            <option value="Aliah University">Aliah University</option>
        </select>

        <textarea name="address" id="address" cols="30" rows="10" style="display: block; border: 2px solid black; border-radius: 6px; outline: none; font-size: 20px; width: 100%; margin: 11px 0px; padding: 10px;" placeholder="Enter Your Address" required></textarea>

        <select id="state" name="state" required>
            <option select hidden value="">Select your State Name</option>
            <option value="Andhra Pradesh">Andhra Pradesh</option>
            <option value="Andaman and Nicobar Islands">Andaman and Nicobar Islands</option>
            <option value="Arunachal Pradesh">Arunachal Pradesh</option>
            <option value="Assam">Assam</option>
            <option value="Bihar">Bihar</option>
            <option value="Chandigarh">Chandigarh</option>
            <option value="Chhattisgarh">Chhattisgarh</option>
            <option value="Dadar and Nagar Haveli">Dadar and Nagar Haveli</option>
            <option value="Daman and Diu">Daman and Diu</option>
            <option value="Delhi">Delhi</option>
            <option value="Lakshadweep">Lakshadweep</option>
            <option value="Puducherry">Puducherry</option>
            <option value="Goa">Goa</option>
            <option value="Gujarat">Gujarat</option>
            <option value="Haryana">Haryana</option>
            <option value="Himachal Pradesh">Himachal Pradesh</option>
            <option value="Jammu and Kashmir">Jammu and Kashmir</option>
            <option value="Jharkhand">Jharkhand</option>
            <option value="Karnataka">Karnataka</option>
            <option value="Kerala">Kerala</option>
            <option value="Madhya Pradesh">Madhya Pradesh</option>
            <option value="Maharashtra">Maharashtra</option>
            <option value="Manipur">Manipur</option>
            <option value="Meghalaya">Meghalaya</option>
            <option value="Mizoram">Mizoram</option>
            <option value="Nagaland">Nagaland</option>
            <option value="Odisha">Odisha</option>
            <option value="Punjab">Punjab</option>
            <option value="Rajasthan">Rajasthan</option>
            <option value="Sikkim">Sikkim</option>
            <option value="Tamil Nadu">Tamil Nadu</option>
            <option value="Telangana">Telangana</option>
            <option value="Tripura">Tripura</option>
            <option value="Uttar Pradesh">Uttar Pradesh</option>
            <option value="Uttarakhand">Uttarakhand</option>
            <option value="West Bengal">West Bengal</option>     
        </select>

        <input type="zipcode" name="zipcode" id="zipcode" placeholder="Enter your Zip Code" required>
        
        <select id="country" name="country" required>
            <option select hidden value="">Select Country</option>
            <option value="INDIA">INDIA</option>
        </select>

        <input type="submit" name="submit" value="register now" class="form-btn">

        <p>already have an account? <a href="loginform.php">login now</a></p>

    </form>
</div>
    
</body>
</html>